<a href="https://colab.research.google.com/github/perfectporfoliopablo/Curso-Lenguaje-Orientado-a-objetos-y-bases-de-datos/blob/main/Numpy_pruebas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
a=np.zeros(3)
a

array([0., 0., 0.])

In [ ]:
a=np.ones(4)
a

array([1., 1., 1., 1.])

In [ ]:
a=np.random.rand(4,3)
a

array([[0.26471259, 0.23215837, 0.06623378],
       [0.65157824, 0.42054161, 0.08958926],
       [0.15092227, 0.90390265, 0.9762523 ],
       [0.55979403, 0.71828719, 0.8749337 ]])

In [ ]:
aa=np.empty((4,3))
aa

array([[0.26471259, 0.23215837, 0.06623378],
       [0.65157824, 0.42054161, 0.08958926],
       [0.15092227, 0.90390265, 0.9762523 ],
       [0.55979403, 0.71828719, 0.8749337 ]])

In [ ]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
a=np.arange(2,16)
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
a=np.arange(0,17,6)
a

array([ 0,  6, 12])

In [ ]:
a=np.linspace(0,8,5)
a

array([0., 2., 4., 6., 8.])

In [ ]:
a=np.linspace(0,17,25,dtype=int)
a

array([ 0,  0,  1,  2,  2,  3,  4,  4,  5,  6,  7,  7,  8,  9,  9, 10, 11,
       12, 12, 13, 14, 14, 15, 16, 17])

In [ ]:
a=np.linspace(0,17,25).round(4)
a

array([ 0.    ,  0.7083,  1.4167,  2.125 ,  2.8333,  3.5417,  4.25  ,
        4.9583,  5.6667,  6.375 ,  7.0833,  7.7917,  8.5   ,  9.2083,
        9.9167, 10.625 , 11.3333, 12.0417, 12.75  , 13.4583, 14.1667,
       14.875 , 15.5833, 16.2917, 17.    ])

In [ ]:
a=np.array([2,1,5,3,7,4,6,8])
np.sort(a)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a=np.array([2,1,5,3,7,4,6,8])
np.sort(a)[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1])

In [ ]:
a=np.array([[5,2,8],[1,3,6]])
a

array([[5, 2, 8],
       [1, 3, 6]])

In [ ]:
np.sort(a,axis=0)

array([[1, 2, 6],
       [5, 3, 8]])

In [ ]:
a=np.array([[5,2,8],[1,3,6]])
np.sort(a,axis=1)

array([[2, 5, 8],
       [1, 3, 6]])

In [ ]:
a=np.array([[5,2,8],[1,3,6]])
np.sort(a,axis=1)[:,::-1]

array([[8, 5, 2],
       [6, 3, 1]])

In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

z=np.concatenate((x,y),axis=0)
z

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

z=np.concatenate((x,y),axis=1)
z

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
a=np.array([1,2,3,4,5])
np.delete(a,[1,3])


array([1, 3, 5])

In [ ]:
a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
np.delete(a,2,axis=1)

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
np.delete(a,1,axis=1)

array([[1, 3],
       [4, 6],
       [7, 9]])

In [ ]:
a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
np.delete(a,1,axis=0)

array([[1, 2, 3],
       [7, 8, 9]])

In [ ]:
a=np.array([1,2,3])
np.append(a,[4,5])

array([1, 2, 3, 4, 5])

In [ ]:
a=np.array([[1,2,3],
            [4,5,6]])
np.append(a,[[7,8,9]],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a=np.array([1,2,3,4,5])
np.insert(a,4,33)#inserta el numero 33 en la posicion 4 del array

array([ 1,  2,  3,  4, 33,  5])

In [ ]:
a=np.array([[1,2,3],
            [4,5,6]])
np.insert(a,1,[0,0],axis=1)

array([[1, 0, 2, 3],
       [4, 0, 5, 6]])

In [ ]:
a=np.array([[1,2,3],
            [4,5,6]])
a.ndim

2

In [ ]:
a=np.array([1,2,3])
a.ndim

1

In [ ]:
a=np.array([[1,2,3],
            [4,5,6]])
a.size

6

In [ ]:
a.shape

(2, 3)

In [ ]:
a=np.array([[[1,2,3],
            [4,5,6]],
            [[1,2,3],
             [4,5,6]]])
a.ndim

3

In [ ]:
a.size

12

In [ ]:
a=np.array([1,2,3])
a.shape

(3,)

In [ ]:
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
b=a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
b=a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
d=np.arange(72)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71])

In [ ]:
c=np.reshape(d,(4,3,2,3))
c

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29]],

        [[30, 31, 32],
         [33, 34, 35]]],


       [[[36, 37, 38],
         [39, 40, 41]],

        [[42, 43, 44],
         [45, 46, 47]],

        [[48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65]],

        [[66, 67, 68],
         [69, 70, 71]]]])

In [ ]:
data=np.array([1,2,3,4,5])
data[1]

2

In [ ]:
data[3:]

array([4, 5])

In [ ]:
data[1:4]

array([2, 3, 4])

In [ ]:
data[::]

array([1, 2, 3, 4, 5])

In [ ]:
data[:]

array([1, 2, 3, 4, 5])

In [ ]:
data[-4:]

array([2, 3, 4])

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
print(a<=5)

[[ True  True  True  True]
 [ True False False False]
 [False False False False]]


In [ ]:
cinco=(a>=5)
a[cinco]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a[a>=5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
divisible=a[(a%2==0)&(a>7)]
divisible

array([ 8, 10, 12])

In [ ]:
divisible=a[(a%2==0)| (a<7)]
divisible

array([ 1,  2,  3,  4,  5,  6,  8, 10, 12])

In [ ]:
divisible=a[a%2!=0]
divisible

array([ 1,  3,  5,  7,  9, 11])

In [ ]:
c=a[(a>2)&(a<11)]
c

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
c=a[(a>5)|(a==5)]
c

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
arr1=a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [ ]:
arr1=a[3:8:2]
arr1

array([4, 6, 8])

In [ ]:
a1=np.array([[1,1],
             [2,2]])
a2=np.array([[3,3],
             [4,4]])

In [ ]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
np.concatenate((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [ ]:
x=np.arange(1,49).reshape(4,12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48]])

In [ ]:
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16],
        [25, 26, 27, 28],
        [37, 38, 39, 40]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20],
        [29, 30, 31, 32],
        [41, 42, 43, 44]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24],
        [33, 34, 35, 36],
        [45, 46, 47, 48]])]

In [ ]:
np.hsplit(x,3)[2]

array([[ 9, 10, 11, 12],
       [21, 22, 23, 24],
       [33, 34, 35, 36],
       [45, 46, 47, 48]])

In [ ]:
arr=np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

result= np.hsplit(arr,2)

print('Array original: ')
print(arr)

print('\nResultado de hsplit():')
print(result)

Array original: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Resultado de hsplit():
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


In [ ]:
np.hsplit(x,(3,5))

[array([[ 1,  2,  3],
        [13, 14, 15],
        [25, 26, 27],
        [37, 38, 39]]),
 array([[ 4,  5],
        [16, 17],
        [28, 29],
        [40, 41]]),
 array([[ 6,  7,  8,  9, 10, 11, 12],
        [18, 19, 20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34, 35, 36],
        [42, 43, 44, 45, 46, 47, 48]])]

In [ ]:
arr1=np.array([1,2])
arr1

array([1, 2])

In [ ]:
arr2=np.ones(2, dtype=int)
arr2

array([1, 1])

In [ ]:
arr1+arr2

array([2, 3])

In [ ]:
arr1-arr2

array([0, 1])

In [ ]:
arr1*arr1

array([1, 4])

In [ ]:
arr1/arr1

array([1., 1.])

In [ ]:
a=np.array([1,2,3,4])
a.sum()

10

In [ ]:
b=np.array([[1,1],[2,2]])
b

array([[1, 1],
       [2, 2]])

In [ ]:
b.sum(axis=0)

array([3, 3])

In [ ]:
b.sum(axis=1)

array([2, 4])

In [ ]:
data=np.array([1.0,2.0,3.0,4.0,5.0])
data*1.6

array([1.6, 3.2, 4.8, 6.4, 8. ])

In [ ]:
data.max()

5.0

In [ ]:
data.min()

1.0

In [ ]:
data.mean()

3.0

In [ ]:
data.prod()

120.0

In [ ]:
data.std()

1.4142135623730951

In [ ]:
a=np.array([1,15,60,390,550,34,7,342,100])
a.mean()

166.55555555555554

In [ ]:
a.std().round(4)

193.4851

In [ ]:
data=np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
data[0,1]

2

In [ ]:
data[0:2]

array([[1, 2],
       [3, 4]])

In [ ]:
data[0:3,0]

array([1, 3, 5])

In [ ]:
data.max(axis=0)

array([5, 6])

In [ ]:
data.max(axis=1)

array([2, 4, 6])

In [ ]:
data1=np.array([[1,2],[3,4]])
data2=np.array([[1,1],[1,1]])

data1 + data2

array([[2, 3],
       [4, 5]])

In [ ]:
data1 @ data2 #multiplicacion

array([[3, 3],
       [7, 7]])

In [ ]:
np.dot(data1,data2) #multiplicacion

array([[3, 3],
       [7, 7]])

In [ ]:
data1=np.array([[1,2],[3,4],[5,6]])
data2=np.array([1,1])
data1 + data2

array([[2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[::2,::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
data=np.arange(0,96).reshape(2,4,3,4)
data

array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]],

        [[24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35]],

        [[36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]]],


       [[[48, 49, 50, 51],
         [52, 53, 54, 55],
         [56, 57, 58, 59]],

        [[60, 61, 62, 63],
         [64, 65, 66, 67],
         [68, 69, 70, 71]],

        [[72, 73, 74, 75],
         [76, 77, 78, 79],
         [80, 81, 82, 83]],

        [[84, 85, 86, 87],
         [88, 89, 90, 91],
         [92, 93, 94, 95]]]])

In [ ]:
data[1,[0,1],[0,2],::2]

array([[48, 50],
       [68, 70]])

In [ ]:
data[0,0,0,::]

array([0, 1, 2, 3])

In [ ]:
data[0,0,[0,0,0,0,1,2],[0,1,2,3,3,3]]

array([ 0,  1,  2,  3,  7, 11])

In [ ]:
rng=np.random.default_rng()
rng.integers(4,11,size=(3,4),endpoint=True)

array([[ 6,  9,  9,  4],
       [10,  7,  6,  7],
       [11,  5,  5,  9]])

In [ ]:
a=np.array([11,11,11,11,11,11,11,11,14,16,16,16,16,16,16])
u=np.unique(a)
u

array([11, 14, 16])

In [ ]:
arr=np.array([[2,4,6,2,2,5,6,6,7],[8,4,4,3,2,3,2,7,4]])
unicos,ocurren=np.unique(arr, return_counts=True)
print(unicos)
print(ocurren)

[2 3 4 5 6 7 8]
[5 2 4 1 3 2 1]


In [ ]:
data.reshape(2,3)


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
data.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a=np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
a=np.arange(20).reshape(5,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
a.transpose()

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [ ]:
a.T

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [ ]:
a=np.array([1,2,3,4,5,6,7,8])
np.flip(a)

array([8, 7, 6, 5, 4, 3, 2, 1])

In [ ]:
a2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.flip(a2)

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [ ]:
solofilas=np.flip(a2,axis=0)
solofilas

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [ ]:
solocolumnas=np.flip(a2,axis=1)
solocolumnas

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [ ]:
x=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a=np.array([[2,3,-1],[4,1,2],[3,-2,1]])
b=np.array([7,4,10])
x=np.linalg.solve(a,b)
x

array([ 3.74074074, -1.7037037 , -4.62962963])

In [ ]:
a=np.array([[2,3],[4,1]])
b=np.array([7,4])
x=np.linalg.solve(a,b)
x

array([0.5, 2. ])

In [ ]:
a=np.array([[1,2],[3,4]])
a_inversa=np.linalg.inv(a)
print('Matriz a:')
print(a)
print('\nInversa de la matriz a:')
print(a_inversa)

Matriz a:
[[1 2]
 [3 4]]

Inversa de la matriz a:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
a=np.array([[1,2],[3,4]])
ainv=np.array([[-2,1],[1.5,-0.5]])
a@ainv

array([[1., 0.],
       [0., 1.]])

In [ ]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[10,11,12],[13,14,15],[16,17,18]])
A+B

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [ ]:
A@B

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [ ]:
A-B

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [ ]:
A.sum()

45

In [ ]:
B.sum()

126

In [ ]:
A.prod()

362880

In [ ]:
B.prod()

17643225600

In [ ]:
C=np.array([[1,2,3],[4,5,6],[8,8,9]])
C_inversa=np.linalg.inv(C)

In [ ]:
C_inversa@C

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
det=np.linalg.det(C)
det

-2.9999999999999996

In [ ]:
array1=np.arange(1,26).reshape(5,5)
array1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
array1[[2,2,3,3],[0,1,0,1]]

array([11, 12, 16, 17])

In [ ]:
array1[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])